---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: ceph
    daemon: rgw
  name: ceph-rgw
  namespace: ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph
      daemon: rgw
  template:
    metadata:
      name: ceph-rgw
      namespace: ceph
      labels:
        app: ceph
        daemon: rgw
    spec:
      nodeSelector:
        node-type: storage
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values: ["ceph"]
              - key: daemon
                operator: In
                values: ["rgw"]
            topologyKey: kubernetes.io/hostname
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: default
      volumes:
        - name: ceph-conf
          secret:
            secretName: ceph-conf-combined
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
        - name: ceph-bootstrap-rgw-keyring
          secret:
            secretName: ceph-bootstrap-rgw-keyring
        - name: ceph-bootstrap-rbd-keyring
          secret:
            secretName: ceph-bootstrap-rbd-keyring
      containers:
        - name: ceph-rgw
          #image: ceph/daemon:latest
          image: slpcat/ceph-daemon:ubuntu16.04
          ports:
            - containerPort: 8088
          env:
            - name: CEPH_DAEMON
              value: RGW
            - name: RGW_CIVETWEB_PORT
              value: "8088"
            #- name: RGW_NAME
            #  value: myrgw
            #- name: RGW_ZONEGROUP
            #  value: ""
            #- name: RGW_ZONE
            #  value: ""
            - name: KV_TYPE
              value: k8s
            - name: CLUSTER
              value: ceph
            #- name: DEBUG
            #  value: verbos
          volumeMounts:
            - name: ceph-conf
              mountPath: /etc/ceph
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds
            - name: ceph-bootstrap-rgw-keyring
              mountPath: /var/lib/ceph/bootstrap-rgw
            - name: ceph-bootstrap-rbd-keyring
              mountPath: /var/lib/ceph/bootstrap-rbd
          livenessProbe:
              httpGet:
                path: /
                port: 8088
              initialDelaySeconds: 120
              timeoutSeconds: 5
          readinessProbe:
              httpGet:
                path: /
                port: 8088
              timeoutSeconds: 5
          resources:
            requests:
              memory: "500Mi"
              cpu: ".5"
            limits:
              memory: "4Gi"
              cpu: "4"
